ci:
  collect:
    url:
      - http://localhost:3000/
      - http://localhost:3000/tags.html#symfony
      - http://localhost:3000/10-calendriers-de-l-avent-a-suivre.html
    numberOfRuns: 2
    staticDistDir: "./_site"

  assert:
    preset: lighthouse:recommended
    assertions:
      first-contentful-paint:
        - warn
        - maxNumericValue: 2500
          aggregationMethod: optimistic
      interactive:
        - warn
        - maxNumericValue: 5000
          aggregationMethod: optimistic
      uses-long-cache-ttl: off

  upload:
    target: temporary-public-storage
