# Permalinks
permalink: /:title

# Setup
title: j0k3r.net
paginate: 100
url: "https://www.j0k3r.net"
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-pwa-plugin

# Assets
sass:
  style: :compressed

# Build settings
markdown: kramdown

# About
author:
  name: Jérémy Benoist
  url: https://www.j0k3r.net

future: false

sidebar_home_link: true

theme: jekyll-theme-hydeout

exclude:
  - vendor
  - Gemfile*
  - README.md

include:
  - _redirects

pwa:
  sw_src_filepath: assets/js/service-worker.js
  sw_dest_filename: service-worker.js
  dest_js_directory: assets/js
  precache_recent_posts_num: 5
