# Permalinks
permalink: /:title/

# Setup
title: j0k3r.net
paginate: 100

plugins:
  - jekyll-feed

# Assets
sass:
  style: :compressed

# Build settings
markdown: kramdown

# About
author:
  name: Jérémy Benoist
  url: https://www.j0k3r.net

future: false

sidebar_home_link: true

theme: jekyll-theme-hydeout

exclude:
  - vendor
  - Gemfile*
  - README.md

include:
  - _redirects
