# Permalinks
permalink: /:title

# Setup
title: j0k3r.net
paginate: 100
url: "https://www.j0k3r.net"
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Assets
sass:
  style: :compressed

# Build settings
markdown: kramdown

# About
author:
  name: Jérémy Benoist
  url: https://www.j0k3r.net

future: false

sidebar_home_link: true

theme: jekyll-theme-hydeout

exclude:
  - vendor
  - Gemfile*
  - README.md

include:
  - _redirects

cloudinary:
  cloud_name: j0k
  verbose: true

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
