name: Linter

on:
  push:
    branches: [ blog ]
  pull_request:
    branches: [ blog ]

jobs:
  biome:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - run: yarn install

      - run: yarn lint
