name: Linter

on:
  push:
    branches: [ blog ]
  pull_request:
    branches: [ blog ]

jobs:
  biome:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Cache Eleventy .cache
        uses: actions/cache@v4
        with:
          path: ./.cache
          key: ${{ runner.os }}-eleventy-fetch-cache

      - run: yarn install

      - run: yarn lint
